updates

diff --git a/bin/search b/bin/search
--- a/bin/search
+++ b/bin/search
@@ -14,47 +14,48 @@ fi
 
 case $1 in 
     "start")
-        if [ -f "var/index.sqlite3" ]
+        ./bin/index status
+        status = $?
+        if [ ! -f "var/index.sqlite3" ]
+        then 
+            # database does not exist
+            echo "Error: can't find search database var/index.sqlite3"
+            echo "Try: ./bin/indexdb create"
+            exit 1
+        elif [$status -eq 1]
+        then 
+            # index server is stopped use ./bin/index status
+            echo "Error: index server is not running"
+            echo "Try ./bin/index start"
+        elif [pgrep -f "flask run --host 0.0.0.0 --port 8000" &> /dev/null]
         then
+            # search server is already running
+            echo "Error: search server is already running"
+        else
             echo "starting search server ..."
             mkdir -p var/log
             rm -f var/log/search.log
-            FLASK_APP=search flask run --host 0.0.0.0 --port 8000 &> var/log/search.log &        else
-            echo "Error: can't find search database var/index.sqlite3"
-            echo "Try: ./bin/indexdb create"
+            FLASK_APP=search flask run --host 0.0.0.0 --port 8000 &> var/log/search.log &
         fi
         ;;
     "stop")
-
-        ;;
-    "stop")
-
+        echo "stopping search server ..."
+        pkill -f 'flask run --host 0.0.0.0 --port 8000' || true
         ;;
     "restart")
-        echo "stopping index server ..."
-        pkill -f "flask run --host 0.0.0.0 --port 9000" || true
-        pkill -f "flask run --host 0.0.0.0 --port 9001" || true
-        pkill -f "flask run --host 0.0.0.0 --port 9002" || true
-        echo "starting index server ..."
+        echo "stopping search server ..."
+        pkill -f 'flask run --host 0.0.0.0 --port 8000' || true
+        echo "starting search server ..."
         mkdir -p var/log
-        rm -f var/log/index.log
-        FLASK_APP=index INDEX_PATH="inverted_index_0.txt" flask run --host 0.0.0.0 --port 9000 >> var/log/index.log 2>&1 &
-        FLASK_APP=index INDEX_PATH="inverted_index_1.txt" flask run --host 0.0.0.0 --port 9001 >> var/log/index.log 2>&1 &
-        FLASK_APP=index INDEX_PATH="inverted_index_2.txt" flask run --host 0.0.0.0 --port 9002 >> var/log/index.log 2>&1 &
+        rm -f var/log/search.log
+        FLASK_APP=search flask run --host 0.0.0.0 --port 8000 &> var/log/search.log &
         ;;
     "status")
-        set +o pipefail
-        NPROCS=$(pgrep -f "flask run --host 0.0.0.0 --port 900[0-2]" | wc -l)
-        set -o pipefail
-        if [ "$NPROCS" -eq 3 ]; then
-        echo "index server running"
-        exit
-        elif [ "$NPROCS" -eq 0 ]; then
-        echo "index server stopped"
-        exit 1
+        if pgrep -f "flask run --host 0.0.0.0 --port 8000" &> /dev/null
+        then 
+            echo "search server running"
         else
-        echo "index server error: found ${NPROCS} processes, expected 3"
-        exit 2
+            echo "search server stopped"
         fi
         ;;
     *)
